### ISSUE TITLE
Missing godot refcounted module

### ISSUE THREAD

**Issue by Dairoe** [godot-dlang/godot-dlang#102]
when building with dub:

`Error: unable to read module refcounted
`

seems this module doesn't appear to be inside the godot src api folder.

**Comment by Superbelko** [comment]
Do you have bindings generated from godot --dump-extensions-api?

**Comment by Superbelko** [comment]
Well that's strange, it was supposed to go into dub cached package but looks like it was fell off on the long way from beta.

For now just copy classes into dub godot-dlang cached package, you can get the path from `dub list` command and search for package name.

**Comment by Superbelko** [comment]
Yeah unfortunately we are dealing with tons of templates, if you have less than 8gb ram you probably need -lowmem switch for DMD, and LDC... well no idea if they have it or anything like that yet.

Just to be clear, you have cloned the repo, grabbed the extension_api.json from godot, then generated the bindings inside of that repo, right? If so, there should be classes folder with all this generated bindings in there.

**Comment by Superbelko** [comment]
godot-dlang itself is a static library, generator is an executable, any game extensions you are building has to be dynamic libraries.

Generated bindings used by both godot-dlang AND your extensions, because these bindings are generated for specific engine version depending on your workflow you might want to put them in your project (and add to source path in your dub project, if work on per project basis with different engine versions), but generally you share them across one engine version by putting under godot-dlang library source.

These bindings have to be regenerated when upgrading dub package or godot itself, sometimes on master we do update generator to fix bugs so that is another situation when to re-generate them.
