### ISSUE TITLE
Make Godot types class instead of struct

### ISSUE THREAD

**Issue by al1-ce** [godot-dlang/godot-dlang#11]
I see that all internal Godot nodes are made types which poses problems and requires this GodotScript wrapper class, but might it be possible to make them their own classes?

> Maybe, current structure is direct successor of godot-d design.
> 
> I haven't touched that part because of avoiding doing breaking changes. But since original project seems to be completely abandoned maybe it is time to move on.

**Comment by al1-ce** [comment]
In extension_api.json class declarations have field "inheritance", would need to look it up and set as child. Plus import it and instantiate with "new" if it comes up

**Comment by Superbelko** [comment]
Since D scripts are all classes it seems nothing stops from making generator emit regular D classes instead of this binding tables, but...

There is one little issue, there is no way to avoid using CRTP/helper template or mixin altogether to register all this stuff automatically.

So it will either be
```d
// here GodotScript will take care of registration and all
class MyCoolScript : GodotScript!Node
{
  // code
}
```

OR

```d
class MyCoolScript : Node
{
   // so now we have to write this stupid mixin in every class, how is that an improvement?
   mixin registerScript;

   // code
}
```

**Comment by al1-ce** [comment]
I don't see any registeting code in GodotScript

Register itself happens here
https://github.com/godot-dlang/godot-dlang/blob/25c00a60832585fe766ef1f269754450a2bc0d9b/src/godot/api/register.d#L71
Which u need to supply class name, so there's no need for any mixins

**Comment by Superbelko** [comment]
Yeah ok maybe, it was in old godot-d then, basically it was loading function pointers and maybe something else.

If that is gone then it should be possible to drop GodotScript template and just use regular D classes, this however will make it completely unusable with betterC if not yet.

Binding struct should be made static to be able to use outside of classes and class methods should simply forward all calls to that struct.

There is one problem however... godot loads virtual functions only once and I have no idea how hard it would be to correctly implement virtual calls across D/godot especially in nested hierarchies.

**Comment by al1-ce** [comment]
@Superbelko tried solving this issue but got kind of very stuck
https://github.com/al1-ce/godot-dlang/tree/testclasses

Git complains about stuff not having `opCall` when casting to variant

Honestly I have a feeling that we'd have to rewrite everything to make it work with classes

**Comment by Superbelko** [comment]
I suggest we drop that idea.
As you might noticed this is not just a matter of replacing "struct" with "class" everywhere in source files.
There is gigantic semantic gap between the two, without some dramatic rewriting this won't work. 

What's more to it is that I don't see any real benefit of doing this, but we will lose the ability to go betterC if needed and this for example might be necessary for platforms such as WebAsm.

Additionally if all this is just to be able to write `class MyNode : Node3d` instead of `class MyNode : GodotScript!Node3d` then we need a better reason.

Btw interface would be a better option because there is no data for godot classes on D side at all, except the GodotObject itself which must have at least one field.

**Comment by al1-ce** [comment]
I mean.. Yea, this has to be full rewrite. Also a point for having classes is lsp autocompletion. Right now you basically writing blindly which is not as comfortable as it could be

I guess this will be on a back burner until current solution will break so much that it'd be better to rewrite everything from scratch

Also interface ain't really gonna cut it since be have to do calls to godot's methods or idk. Current codebase is confusing and I have a huge itch to just figure out how cpp bindings work anf just translate them

**Comment by al1-ce** [comment]
https://lsferreira.net/posts/zet-1-classes-betterc-d/

Just gonna drop it here for myself for later

**Comment by Superbelko** [comment]
PR #158 is in, closing this as completed.

This PR brings initial support for classes:
- added `-c` (--classes) flag for binding generator 
- added `classes` dub config, see `test` demo project on how to add it in your projects
- internally it uses new version `USE_CLASSES` in case if you need to version branch your code

For demo project there is added configuration matching the primary dub configuration named `classes`, in order to use it one need to regenerate bindings by running generator with `-c` flag and then build demo:
- `dub run :generator -- -j path/to/extension_api.json -o -c`
- `dub build :test -c classes`

Classes version is not 100% compatible with regular one, for example there is difference in null checks (`is` operator vs `==`), inheriting godot scripts now requires `override` keyword for overriding methods (including `_ready`), and don't forgot to call base class methods if you are going to extend parent class behavior.
