### ISSUE TITLE
Full rewrite - discussion

### ISSUE THREAD

**Issue by al1-ce** [godot-dlang/godot-dlang#149]
Related: #11 #12 #16 #47

## Topic 
Is it worth rewriting whole thing from "scratch"?

### Pros
- cleaner codebase
- would probably solve some/all of mentioned issues
- ... (gotta figure out more)

### Cons
- it's a full rewrite which is a big con
- most breaking thing that could be done
- ... (don't have anything else yet)

## How
Probably referencing cpp bindings since cpp is closest to D from all languages that there are. Only problem with that is how cpp internally works (i.e classes are glorified structs, everything is a pointer and so on)

## Why
- Codebase is a big mess
- Above issues
- gc/nogc (see below) 

Initially godot-d was written with particular mindset of keeping it as nogc as possible which ain't bad, but it creates an issue of having to know almost everything at compile time. It's great and all, but we're talking about godot which uses own interpreted scripting language as main means of coding, so speed isn't really an issue here. 

## ... 
So, now question is what to do with all that. 

Is it worth spending time rewriting or is it worth spending time trying to poke existing code until it works?

**Comment by Superbelko** [comment]
If all this about making use of classes instead of templates then it doesn't have to be a full rewrite. 
Any kind of __rewrite is no go__ for me, I have my fork and can live pretty much with it.

* `nogc` can be used with classes, there is no problem with it, and we mostly do this as internally all object allocations done by godot (the gc is still used by normal D code like array ops and string concatenations and such).

* Sure there is problems with tangled codebase, and we can probably decouple core variant types from what we have in classes like String, but not much as this type is already more like a thin wrapper.

* There is indeed a problem with binding generator w.r.t. JSON serialization, just look at the hacks used to make `Type` instances surely unique, this type of stuff is generally must be fixed by the use of real SRP separation, i.e. separate DTO for deserializer and tree walk generator, but will it really make it better?

* Biggest problem is platforms without `D runtime` such as HTML(WebAsm) and smaller consoles like Nintendo Switch, without it there is no way to use D classes, extern(C++) classes still possible in such environments but they have extremely messy class layout and vtable esp. when interfaces involved, also it will complain on string parameters "dis is not supported in extern(c++)".

* Also the bindings is already pretty much how it works in C++, the difference is the use of hardcore CTFE to autoregister everything, and a complicated GDExtension call mechanism due to godot quirks on how it passes the data in native calls, if you can fix that native calls complexity, then sure please do, it will benefit every user of godot-dlang.

You still think this is a 100% must do task to convert it to classes? The biggest problem will be the core GodotObject class, but I expect it to be around 1k loc change, no full rewrite needed.

And finally, any rewrite that was not ended up in the same mess is quite rare, are you smart enough to remember every possible edge case and design a new system that works?

**Comment by al1-ce** [comment]
It's less about classes and more about codebase

I have absolutely no idea how it works and honestly can only understand some small parts. And there's a bunch of other not so good stuff related 

I guess I could try on my own private branch, not touching master at all

**Comment by Superbelko** [comment]
Sure then, let's improve it, but I must tell you the current state is not because we wanted it that way but because of innate complexity of the problem.

Let's avoid classes until the code is all nice and tidy, ok? Like i said, this isn't the problem to do and the scope is more or less just few thousands lines of code, but the project is years of work and there is no way to build this from scratch and not to mess up.

**Comment by Superbelko** [comment]
@al1-ce do you have discord? I found my old account, you can ping me there, I'll reply when I can.

**Comment by al1-ce** [comment]
@Superbelko yea, I do it's `@silyneko`

**Comment by Superbelko** [comment]
Ok, i've sent you a friends request, fell free to delete these messages when you are done.
