### ISSUE TITLE
Editor Module

### ISSUE THREAD

**Issue by al1-ce** [godot-dlang/godot-dlang#18]
Need to be investigated if it's possible to have bindings as editor plugin/scripts (something c# has)
Also might be useful to look at [Haxe C# Plugin](https://github.com/HaxeGodot/editor-plugin)

**Comment by Superbelko** [comment]
I don't get what do you mean by that, but in theory it should be possible to go down to engine subsystems level like integrating your own physics/graphics/audio "server".

If you look for bindings there is a lot of Editor* classes as well so it should be possible now.

**Comment by al1-ce** [comment]
I meant looking into possibility of making module, like ECMAScript guys doing

Also this issue gonna hang for a while coz c# is going to become an extension or something and this might spawn some info how to integrade D with Godot much closer

**Comment by Superbelko** [comment]
Can you describe specifically what do you mean by "much closer" ?
Because GDExtension aims to be transparent to all scripting sides, you can already use D classes in gdscript and so on, have type information about them in the editor and so on.

**Comment by al1-ce** [comment]
Specifically I mean having D integrate with editor as GDScript or c# or js (via module) does
You create scripts and you attach them.
Currently D behaves more like plugin/addon, but it'd be nice to have "native" support in-engine

**Comment by al1-ce** [comment]
As I said, this issue going to hang around until mono is moved out of it's separate build into gdextension space
Going try find something that talks about this

**Comment by Superbelko** [comment]
You can have D script on scene as an object directly without "attaching".
You can have D script used in scripts and other places treated same way as gdscript.

So what the difference then?

**Comment by al1-ce** [comment]
Let's come back to that much much later. I put this issue only for tracking/reminder too look into some possibilities

**Comment by Superbelko** [comment]
This also relates to #12 probably, but here is my point - Whatever you do please keep in mind separation of concerns, this is something easily ignored (and confused with?) in favor of "usability".

Basically a user(game developer in this case) only interfaces with a very small part of the engine/API, in ideal world your product(a game) should not depend on third party code (engine API), you should extract all types that interacts with them in a separate program module to isolate the risks, etc...
When this concept is broken there is a lot of side effects such as inability to upgrade to a newer (incompatible) engine versions, inability to gradually migrate code unit by unit, and so on...

This kind of issues is a norm in gamedev, Unity users suffers from that, Unreal users suffers from that, and Godot users too blindly copied that approach with С#.

Key point: **ideally game implementation code should not be directly dependent on a engine API**

So, why bother with #12 then? You should not expose your entire class to godot without need, and if you do this a lot - something went wrong, right?

**Comment by al1-ce** [comment]
#12 with right implementation would expose only predefined methods (ak _ready, _process etc)
It's only a minor convince for use with common and solid point in api
_ready is always will be godot's _ready, so why not do it automatically?

**Comment by Superbelko** [comment]
Oh, ok then. 
Let's just hope it won't introduce flaky behavior when some methods most used by the users work that way and so they decided that it works like that by default, except it is not, and then needles painful debugging starts... Not in this particular case but yeah.

**Comment by al1-ce** [comment]
https://docs.godotengine.org/en/latest/classes/class_script.html

It might be possible to create custom scripts but I'm not really sure how yet

**Comment by Superbelko** [comment]
Why do you so obsessed with making "module" or script file or whatever? Just to show it up in the content browser? 
Well, it is already transparently integrated with the engine, it is saved in scripts, on scenes, wherever else, correctly, and you don't have to do any extra work to use it.

**Comment by al1-ce** [comment]
I'm just trying to familiarise myself with how it all works
Also looking at possibilities and how it might be done if needed

It's called research. And research I do

**Comment by al1-ce** [comment]
Another reason why I keed returning to that is #26
C# somehow does avoids that and I want to know how

**Comment by Superbelko** [comment]
Mono runtime can have have hot reload within runtime and it is one of the reasons Unity still using it(do they?), tbh I have no idea how they would even integrate hot reloading/patching with .NET 6 because this was extremely painful if not possible at all in prior .NET Core branch.

Though I'm not that active .NET user and my knowledge here is quite limited or even outdated.


for #26 there is only two options:
1) do it with a button inside godot editor, manual labor at its best
2) add dub prebuild command to call editor host to do unload and load it back on postbuild command

**Comment by al1-ce** [comment]
I looked up and you kind of can reload dll on the fly with dotnet, it's not pretty but you can

And yea, for #26 i think would be good to use both of those options, or rather integrate 2 into 1
Use pre/postbuild commands to unload/load, but also have editor addon that would call dub from shell to ask to build
Though it'd require some tinkering and possibly couple of settings (ak path to dub, default compiler, yada yada yada)

And about having scripts, I, personally, would kind of prefer having things as is, BUT
But the only concern of mine is picker clutter
Imagine, you wave huge game with tons of custom scripts. How would it look when you'd pick node type in editor? It'd be a mess
That's why I'm trying to see what can be done. Scripts are scripts because reasons

**Comment by Superbelko** [comment]
I wasn't talking about reloading DLL on the fly, but patching classes itself on the fly, but it doesn't matter for us in any case.

I am not strictly against this but it is not top priority thing, not even middle one. 

Also from my experience the only kind of people who will work in the editor is scripters who already has decent background and doesn't really care if it is there or not. 
Another kind of people is experts who set up animations, makes particle effects, materials/shaders and that is probably it... 

All other people will generally avoid touching editor at all. Be it a level designers or sound designers, they will likely ever use only their preferred tools, like blender/maya/max or WWISE editor for sound effects.

Maybe in AAA studios they have to work within the editor because of work process requirements, but hobbyists people? Unlikely, heard to many complains from the team even for Unreal Engine...

**Comment by al1-ce** [comment]
> I am not strictly against this but it is not top priority thing, not even middle one.

That I agree on. I'm just taking a short break and some ideas pop up in my head and I look into them.

Currently theres much more stuff that needs attention. For example, I'm mentally preparing to go wild to try to rename most of functions so they better fit their purpose. Same for modules
Plus there's a million if else statements without brackets which isn't really ideal thing
And so on and so forth just improving readability.

**Comment by SpiceyWolf** [comment]
The C# editor integration in previous version with mono was only mildly okay... its pretty steamy hot garbo with the dotnet 6 edition.. also in C# the mono/net framework always did a weird runtime build of the binaries, they werent really 'fully built' in the dll or exe that you pass along... so the binaries it would load up are a temp one dumped somewhere in your tmp files.. I assume dotnet 6 because of the fancy lower level builder and per-platform pre-specification thats not the case, last i checked with trying to learn about hot reloading in C# when i was trying to decide on something like CsScript for a live dev system for an orpg engine that C# was rather jank with the 'unloading' part... you can tell it to reload memory, but not really free it explicitly without killing the app.
