### ISSUE TITLE
Is this limited to betterC or does it have the GC and other conveniences of normal D?

### ISSUE THREAD

**Issue by Zireael07** [godot-dlang/godot-dlang#55]
Title

**Comment by al1-ce** [comment]
It has GC. Original godot-d was a betterc and there might be some traces of it, but not much

**Comment by Superbelko** [comment]
My vision is that we don't strictly tied to make everything nogc in code base but should avoid it as much as possible in critical paths, i.e. class registration does uses GC simply because it would take much more effort to do it completely nogc without much benefit, in the end however even this part will probably be nogc.

The primary game loop however should avoid GC collections, but should allow the users do what they want without forcing anything on them.

**Comment by al1-ce** [comment]
Would you think that a gamedev using godot would care for nogc?
I mean, the option is rather nice but most of people, aside from selected few heavy optimisation, would not really worry about manually managing memory. Again, look at gdscript or c#, gc full on
Plus for nogc folks cpp would be much better choice

**Comment by Superbelko** [comment]
Yes it does matter, but note that it is different from just slapping `@nogc` attribute to every function and call it GC-free.
What is really important is that inside a game loop calling godot generally should not pause for garbage collection.

Comparing D GC with C# GC is like comparing apples to oranges, they are just orthogonal to each other. 
* With D's GC you can only have roughly about 100 Mb of scanned heap size[1] to maintain 60 FPS (well, maybe more now, haven't measured for 2 years now)
* It seems a big amount of memory for filling it up with just objects(references, not game objects), but in practice it will likely start to choke on about 10k objects

Also there is no real point about 'most' projects, imagine a pause that leads to missing input in `osu!`, or similar situation in a multiplayer game(dota maybe?) when your shield ability activation delayed due to GC pause and you are ded, or fast paced 2d shooter game in a similar scenario, would you enjoy this kind of stuff in a game you are playing? 
And this kind of games and genres is not even AAA.

In any case we are on higher ground compared to purely D game engine because we only talk to the engine and it does all the stuff. To not leverage this advantage is like, i don't know, like not taking a free coke in a supermarket receipt bonus.

[1] - just the size of the class instances and/or other tracked references, not the whole process memory.
