### ISSUE TITLE
Current useability

### ISSUE THREAD

**Issue by SpiceyWolf** [godot-dlang/godot-dlang#56]
Since the repo has been silent for almost 2 weeks, I'm wondering how useable its current iteration seems to be for a project? If said project is going to be in development for a good while and mem leaks arent an immediate concern, think it is ready for that?

**Comment by al1-ce** [comment]
Well, if you're going to start project expect to do a lot of hacks for bugs like #3, #4, #5
Plus expect more bugs to pop up, but overall go for it
I'd say rn it's somewhat usable, albeit certainly not production ready 

And about silence, now I'm currently doing a couple of my own projects and Superbelko probably busy too. It doesn't meen that godot-dlang is immediately abandoned, it's just not n.1 on the list

**Comment by SpiceyWolf** [comment]
Oh no xD I didnt think it was abandoned... just wasnt sure if yall got busy or it hit a fairly stable point and u were waiting for feedback about probs or somethin

**Comment by al1-ce** [comment]
Feedback is always welcome, but yea, got busy
Stable point will be when #19 will be at least 80/90% completed

**Comment by Superbelko** [comment]
Well, honestly the current usability hasn't been evaluated yet, feature-wise it is mostly works, and GDExtension features coverage easily passes over 80%, basically 2 major issues - string/array ref counting broken(mem leaks), typed arrays is not yet implemented.
Another important lacking feature is actual extension unregistration for hot reloading.

As for the usability itself... even though we now have editor extension for reloading the shared libs, simplified strings workflow in D and so on, there is a lot of dark areas that hasn't been discovered yet.

As for the question from the topic

> Since the repo has been silent for almost 2 weeks, I'm wondering how useable its current iteration seems to be for a project? If said project is going to be in development for a good while and mem leaks arent an immediate concern, think it is ready for that?

It seems that there was no changes in GDExtension API for beta7 since beta5, and test project still works fine.

I think it should mostly work, however I personally wouldn't be making the whole game in D, it is just too much PITA compared to godotscript for most game parts except gameplay elements/systems.

For my personal projects for example I would indeed implement some kind of ECS style gameplay systems for an colony building game in D, somewhat like rimworld/oxygen not included/terraria, but again all the glue would be in godotscript - tie data to UI, handle input, route gameplay events, menus, data tables, etc..., and for D ones it would be map tile generators, AI task scheduler/behavior trees, and such.
